openapi: 3.0.0
info:
  title: Devjobs-List
  description: Devjobs web app API
  version: 0.1.9

servers:
  - url: https://devjobs-web-api-production.up.railway.app/api
    description: production server
  - url: http://localhost:5555/api
    description: local server
paths:
  /joblist/{size}/{page}:
    get:
      tags:
        - Joblist
      parameters:
        - name: size
          in: path
          description: The number of jobs per page
          required: true
          schema:
            type: integer
            example: 6
            required: true
        - name: page
          in: path
          description: The page number
          required: true
          schema:
            type: integer
            example: 2
            required: true
      responses:
        "2oo":
          description: Succesfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
