openapi: 3.0.0
info:
  title: Devjobs-List
  description: Devjobs web app API
  version: 0.1.9

servers:
  - url: https://devjobs-web-api-production.up.railway.app/api
    description: production server
  - url: http://localhost:5555/api
    description: local server
paths:
  /joblist:
    get:
      tags:
        - Joblist
      responses:
        "2oo":
          description: Succesfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
